'use client'
import { Rubik } from 'next/font/google'
import { AuthContextProvider } from '../context/AuthContext'
import './globals.css'
import Navbar from './components/Navbar'

// components 

const rubik = Rubik({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Bookmark App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <AuthContextProvider>
          <Navbar />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
