'use client'
import { AuthContextProvider } from '../context/AuthContext'
import './globals.css'
import Navbar from './components/Navbar'
import Topbar from './components/Topbar'


// components
// export const metadata = {
//   title: 'Bookmark App',
//   description: 'Generated by create next app',
// }
function profile_context_visible() {
    
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"GlobalLayout"}>
        <AuthContextProvider>
          <Topbar />
            {children}
            <Navbar />
        </AuthContextProvider>
      </body>
    </html>
  )
}
